export const cardArray = [
  {
    id: 0,
    title: "1й товар",
    price: "170 ₽",
    address: "Казань, р-н Вахитовский",
    date: "10 июля 11:39",
    img: "/img/plenka.png",
  },
  {
    id: 1,
    title: "2й товар",
    price: "1570 ₽",
    address: "Казань, р-н Вахитовский",
    date: "10 июля 11:39",
    img: "/img/plenka.png",
  },
  {
    id: 2,
    title: "3й товар",
    price: "5170 ₽",
    address: "Казань, р-н Вахитовский",
    date: "10 июля 11:39",
    img: "/img/plenka.png",
  },
  {
    id: 3,
    title: "4й товар",
    price: "1702 ₽",
    address: "Казань, р-н Вахитовский",
    date: "10 июля 11:39",
    img: "/img/plenka.png",
  },
  {
    id: 4,
    title: "5й сорт",
    price: "1710 ₽",
    address: "Казань, р-н Вахитовский",
    date: "10 июля 11:39",
    img: "/img/plenka.png",
  },
  {
    id: 5,
    title: "2й сорт",
    price: "1170 ₽",
    address: "Казань, р-н Вахитовский",
    date: "10 июля 11:39",
    img: "/img/plenka.png",
  },
];
